# Generated by Django 3.2.6 on 2021-09-06 14:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(blank=True, default='favicon.png', null=True, upload_to='media/author')),
                ('bio', models.TextField(blank=True, max_length=512, null=True)),
                ('short_bio', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('work', models.TextField(blank=True, max_length=256, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_education', to='authentication.education'),
        ),
        migrations.AddField(
            model_name='author',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='author_languages', to='authentication.Languages'),
        ),
        migrations.AddField(
            model_name='author',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='author_skills', to='authentication.Skills'),
        ),
        migrations.AddField(
            model_name='author',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='author_social_media', to='authentication.SocialMedia'),
        ),
        migrations.AddField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='author_tags', to='authentication.Tags'),
        ),
    ]
